WebApplication1/WebApplication1/Models/Classes/Homepage.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication1.Models.Classes
{
    public class Homepage
    {
        [Key]

        public int Id { get; set; }

        /* Sayfa adı ve ünvan */
        public string PageName { get; set; }

       
        /* Hakkımda */

        public string AboutMe { get; set; }


    }
}

WebApplication1/WebApplication1/Models/Classes/Icon.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication1.Models.Classes
{
    public class Icon
    {
        [Key]
        public int Id { get; set; }

        public string IconName { get; set; }

        public string Link { get; set; }
    }
}

WebApplication1/WebApplication1/Models/Classes/Images.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication1.Models.Classes
{
    public class Images
    {
        [Key]

        public int Id { get; set; }

        /* Projeler */

        public string pic { get; set; }
        public string about { get; set; }
        public string header { get; set; }

    }
}

WebApplication1/WebApplication1/Models/Classes/Slider.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication1.Models.Classes
{
    public class Slider
    {

        [Key]

        public int Id { get; set; }

        /* Slider */

        public string pic { get; set; }
        public string header { get; set; }

        public string firstslider { get; set; }


    }
}

WebApplication1/WebApplication1/Controllers/HomepageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models.Classes;

namespace WebApplication1.Controllers
{
    public class HomepageController : Controller
    {
        // GET: Homepage
        Context c = new Context();
        public ActionResult Index()
        {
            var deger = c.homepages.ToList();
            return View(deger);
        }

        public PartialViewResult images()
        {
            var deger = c.images.ToList();
            return PartialView(deger);
        }
        public PartialViewResult imagesw()
        {
            var deger = c.galeries.ToList();
            return PartialView(deger);
        }
        public PartialViewResult slider()
        {
            var deger = c.sliders.ToList();
            return PartialView(deger);
        }



        public PartialViewResult icons()
        {
            var deger = c.icons.ToList();
            return PartialView(deger);
        }
    }
}

WebApplication1/WebApplication1/Views/Homepage/Index.cshtml
@using WebApplication1.Models.Classes
@model List<Homepage>



@{
    Layout = null;
}

<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Tarık ŞEN</title>

    <link rel="stylesheet" href="~/web-CV/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">

</head>

<div>
    <body>

        <!-- Menü Başlangıç -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container-fluid">
                @foreach (var x in Model)
                {
                    <a class="navbar-brand" href="#carouselExampleIndicators">@x.PageName</a>
                }
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#carouselExampleIndicators" style="transition: 2s; font-size: 20px;">AnaSayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#hakkimizda"style="transition: 2s; font-size: 20px;">Hakkımda</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#projeler"style="transition: 2s; font-size: 20px;">Projeler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#galeri"style="transition: 2s; font-size: 20px;">Galeri</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#iletisim"style="transition:2s; font-size:20px;">İletişim</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Menü Bitiş -->
        <!-- Slider Başlangıç -->
        
                @Html.Action("Slider", "Homepage")
            
        <!-- Slider Bitiş-->
        <!-- Hakkımızda Başlangıç -->

        <section class="p-5 text-center hakkimizda" id="hakkimizda">
            <div class="conteiner">

                <h2 class="mb-5 font-weight-bold">Hakkımda</h2>

                <hr class="ayrac"><i class="fas fa-leaf igri"></i>

                @foreach (var x in Model)
                {
                    <p>
                        @x.AboutMe
                    </p>
                }


            </div>
        </section>

        <!-- Hakkımızda Bitiş     -->
        <!-- Projeler Başlangıç -->

        <section class="p-5 text-center projeler" id="projeler">
            <div class="container">

                <h2 class="mb-5 font-weight-bold">Projeler</h2>

                <hr class="ayrac"><i class="fas fa-leaf ibeyaz"></i>

                @Html.Action("Images", "Homepage")
            </div>
        </section>

        <!-- Projeler Bitiş     -->
        <!-- Galeri  Başlangıç   -->


        <section class="p-5 text-center galeri" id="galeri">
            <div class="container">

                <h2 class="mb-5 font-weight-bold">Galeri</h2>

                <hr class="ayrac"><i class="fas fa-leaf igri"></i>

                @Html.Action("imagesw", "Homepage")
            </div>
        </section>

        <!-- Galeri Bitiş -->
        <!-- İletişim Başlangıç -->
        <section class="p-5 text-center iletisim" id="iletisim">
            <div class="container">

                <h2 class="mb-5 font-weight-bold">İletişim</h2>

                <hr class="ayrac"><i class="fas fa-leaf ibeyaz"></i>


                <form class="col-md-10 text-center m-auto"
                      action="https://formspree.io/f/mwkyopga"
                      method="POST">
                    <div class="form-group row">
                        <label for="" class="col-md-4 aling-self-center"> Ad-Soyad:</label>
                        <input type="text" name="adsoyad" class="form-control col-md-8">
                    </div>
                    <div class="form-group row">
                        <label for="" class="col-md-4 aling-self-center"> Konu :</label>
                        <input type="text" name="konu" class="form-control col-md-8">
                    </div>
                    <div class="form-group row">
                        <label for="" class="col-md-4 aling-self-center"> Email :</label>
                        <input type="text" name="email" class="form-control col-md-8">
                    </div>
                    <div class="form-group row">
                        <label for="" class="col-md-4 aling-self-center"> Mesajınız :</label>
                        <textarea name="mesaj" id="" cols="30" rows="10" class="form-control col-md-8"></textarea>
                    </div>

                    <div class="form-group row">
                        <button type="submit" class="col-md-3 btn btn-primary">Gönder</button>
                    </div>

                </form>
            </div>
        </section>

        <!-- İletişim Bitiş  -->
        <!-- Footer Başlangıç -->

        <div class="bg-dark text-light text-center">
            <p class="aling-middle p-5 mb-0 footer">
                <span>Tüm hakları saklıdır &copy; | 2022</span> <br>
                <span>Desing by Tarık ŞEN</span>
                <br>
                <br>

            </p>
            @Html.Action("Icons", "Homepage")
        </div>



        <!-- Footer Bitiş  -->

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

    </body>
</div>
</html>

WebApplication1/WebApplication1/Views/Homepage/icons.cshtml
@using WebApplication1.Models.Classes
@model List<Icon>

<div>

    @foreach (var x in Model)
    {
        <a href="@x.Link" ><i class="@x.IconName"></i></a>

    }
    <style>
        a{
            font-size:25px;
            padding-left:15px;
            transition:1s;


        }
        a:hover{
            font-size:30px;
              

        }
    </style>
</div>

WebApplication1/WebApplication1/Views/Homepage/images.cshtml
@using WebApplication1.Models.Classes
@model List<Images>


@if (true)
{
    int id = 1;
    id++;
    if (id <= 3)
    {
        <div class="row row-cols-1 row-cols-md-3 g-4">
            @foreach (var y in Model)
            {

                <div class="col">
                    <div class="card h-100 shadow ekipcard">
                        <img src="@y.pic" id="prj" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">@y.header</h5>
                            <p class="card-text"> @y.about</p>
                        </div>
                    </div>
                </div>


            }
        </div>

    }
    if (id == 6 || id >= 3)
    {
        <div class="row row-cols-1 row-cols-md-3 g-4">
            @foreach (var y in Model)
            {

                <div class="col">
                    <div class="card h-100 shadow ekipcard">
                        <img src="@y.pic" id="prj" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">@y.header</h5>
                            <p class="card-text"> @y.about</p>
                        </div>
                    </div>
                </div>


            }
        </div>
    }
    if (id > 6)
    {<div class="row row-cols-1 row-cols-md-3 g-4">
            @foreach (var y in Model)
            {

                <div class="col">
                    <div class="card h-100 shadow ekipcard">
                        <img src="@y.pic" id="prj" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">@y.header</h5>
                            <p class="card-text"> @y.about</p>
                        </div>
                    </div>
                </div>


            }
        </div>

    }
    if (id == 9 || id > 6)
    {
        <div class="row row-cols-1 row-cols-md-3 g-4">
            @foreach (var y in Model)
            {

                <div class="col">
                    <div class="card h-100 shadow ekipcard">
                        <img src="@y.pic" id="prj" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">@y.header</h5>
                            <p class="card-text"> @y.about</p>
                        </div>
                    </div>
                </div>


            }
        </div>
    }
    if (id >9)
    {<div class="row row-cols-1 row-cols-md-3 g-4">
            @foreach (var y in Model)
            {

                <div class="col">
                    <div class="card h-100 shadow ekipcard">
                        <img src="@y.pic" id="prj" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">@y.header</h5>
                            <p class="card-text"> @y.about</p>
                        </div>
                    </div>
                </div>


            }
        </div>

    }
    if (id >12 || id == 15)
    {
        <div class="row row-cols-1 row-cols-md-3 g-4">
            @foreach (var y in Model)
            {

                <div class="col">
                    <div class="card h-100 shadow ekipcard">
                        <img src="@y.pic" id="prj" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">@y.header</h5>
                            <p class="card-text"> @y.about</p>
                        </div>
                    </div>
                </div>


            }
        </div>
    }



}

WebApplication1/WebApplication1/Views/Homepage/imagesw.cshtml
@using WebApplication1.Models.Classes
@model List<Galery>


@if (true)
{
    int id = 1;
    id++;
    <div class="row justify-content-center align-items-center align-self-center">
        @if (id <= 4)
        {
            foreach (var x in Model)
            {


                <div class="col-md-3 ">
                    <figure class="figure">
                        <a href="@x.pic" target="blank">
                            <img src="@x.pic" class="figure-img img-fluid rounded shadow" alt="...">
                        </a>
                    </figure>
                </div>


                if (id > 4 || id >= 8)
                {
                    <div class="row">

                        <div class="col-md-3">
                            <figure class="figure">
                                <a href="@x.pic" target="blank">
                                    <img src="@x.pic" class="figure-img img-fluid rounded shadow" alt="...">
                                </a>
                            </figure>
                        </div>



                    </div>

                }
                

            }
        }
    </div>
}

WebApplication1/WebApplication1/Views/Homepage/slider.cshtml
@using WebApplication1.Models.Classes
@model List<Slider>

<!-- Burada Kaldım slider kısmı tekli ve 3 lü olması gerek -->
<!-- ToDo: -->



@foreach (var x in Model)
{
        <img src="@x.pic" alt="resim" width="100%" height="500px">
   
}